services:
  - type: web
    name: ai-liner
    env: node
    buildCommand: |
      # Install client dependencies and build
      cd client
      npm install
      npm run build
      # The build output is now in ../server/dist
      # Install server dependencies
      cd ../server
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        description: MongoDB connection string
      - key: JWT_SECRET
        generateValue: true
        description: Secret key for JWT token generation
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
