services:
  - type: web
    name: ai-liner
    env: node
    buildCommand: |
      # Print environment info
      echo "=== Build Environment ==="
      echo "Node version: $(node -v)"
      echo "NPM version: $(npm -v)"
      echo "Current directory: $(pwd)"
      ls -la
      
      # Install and build client
      echo "\n=== Building Client ==="
      cd client
      echo "Client directory: $(pwd)"
      ls -la
      
      echo "\nInstalling client dependencies..."
      npm install
      
      echo "\nBuilding client..."
      npm run build
      
      # Verify build output
      echo "\n=== Verifying Build Output ==="
      echo "Build output directory: $(pwd)/dist"
      ls -la dist/ || echo "No dist directory found"
      
      # Create server/public directory if it doesn't exist
      echo "\n=== Setting Up Server Directory ==="
      mkdir -p ../server/public
      
      # Copy build output to server/public
      echo "\nCopying build files to server/public..."
      cp -r dist/* ../server/public/
      
      # Verify files were copied
      echo "\n=== Verifying Server Public Directory ==="
      ls -la ../server/public/
      
      # Install server dependencies
      echo "\n=== Installing Server Dependencies ==="
      cd ../server
      npm install
      
      # Final directory structure
      echo "\n=== Final Directory Structure ==="
      cd ..
      find . -type d -not -path "*/node_modules/*" -not -path "*/.git/*" | sort
      
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        description: MongoDB connection string
      - key: JWT_SECRET
        generateValue: true
        description: Secret key for JWT token generation
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
